### ISSUE TITLE
Implement conditional questions in js

### ISSUE THREAD

**Issue by juliazbyron** [cityofaustin/prototypeform#5]
disclaimers & explanations can use [Bootstrap alerts](https://getbootstrap.com/docs/4.0/components/alerts/).

## page 3 (yourself)
- [x] handle disqualification for under 18 & emergency
  - show disclaimer for now 
- [x] when you click Add explanation, display a textarea for that question.
- [x] disclaimer for no on medications
- [x] disclaimer for yes on humane
- [x] text field for yes existing animal
- [ ] disable form when disqualified 

## page 4 (Availability)
- [x]  availability hour radio, show alert based on selection @mateoclarke

## page 5 (Home)
- [x] if no to own a home, show alert
- [x] if no or maybe to indoors, show alert & show text area
- [x] if yes to kids under 18, show text area

## page 6 (Animal) @mateoclarke
- [x] on page open, only first question appears
- [x] if yes, show the three animal type questions & the can you separate the animals question
- [x] if yes to dogs, show everything down to cats
- [x] if user clicks add another dog, add a new dog info block
- [x] if yes to cats, show everything down to other animals
- [x] if user clicks add another cat, add a new cat info block
- [x] if yes to other animals, show text area
- [x] if no or maybe to separate the animals, show disclaimer

**Comment by mateoclarke** [comment]
oops, didn't mean to close this.

**Comment by juliazbyron** [comment]
So quick @mateoclarke ! I merged the changes, was that correct?

**Comment by juliazbyron** [comment]
@mateoclarke I've done something wrong I can't figure out. I made a new branch for my Home info conditionals, then merged them but now the changes are showing in the prototype but not the master branch code in my editor. Halp plez

**Comment by mateoclarke** [comment]
With Pull Requests #23 & #24, I've finished my portions of this. 

I think "disable form when disqualified" should be added as a new issue with some more details about how that might work. @juliazbyron, you should feel free to close this issue once you complete the Page 5 conditionals or let me or @ifsimicoded know if need help with that.

I'm going to go ahead and merge my PRs to master.

**Comment by mateoclarke** [comment]
It looks like you did knock out the page 5 stuff so I'll go ahead and close this out.
